In [ ]:
import pandas as pd
import numpy as np

In [ ]:
fake = pd.read_csv("Fake.csv")
true = pd.read_csv("True.csv")

print("Fake News Shape:", fake.shape)
print("True News Shape:", true.shape)

Fake News Shape: (23481, 4)
True News Shape: (21417, 4)

In [ ]:
print(fake.columns)
print(true.columns)

Index(['title', 'text', 'subject', 'date'], dtype='str')
Index(['title', 'text', 'subject', 'date'], dtype='str')

In [4]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
fake["label"] = 0
true["label"] = 1

In [7]:
news = pd.concat([fake, true], axis=0)

print(news.shape)

(44898, 5)

In [8]:
news = news.sample(frac=1, random_state=42)

news.head()

,title,text,subject,date,label
22216,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
4436,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
1526,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
1377,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
8995,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [9]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [10]:
news["label"].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [11]:
news.info()

<class 'pandas.DataFrame'>
Index: 44898 entries, 22216 to 15795
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 112.7 MB

In [12]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [13]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Atharwa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
stemmer = PorterStemmer()

In [15]:
stop_words = set(stopwords.words('english'))

In [16]:
def preprocess_text(text):

    text = text.lower()

    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [
        stemmer.stem(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

In [17]:
from tqdm import tqdm
tqdm.pandas()

In [18]:
news["clean_text"] = news["text"].progress_apply(preprocess_text)

  0%|          | 0/44898 [00:00<?, ?it/s]

  0%|          | 36/44898 [00:00<02:05, 358.42it/s]

  0%|          | 116/44898 [00:00<01:12, 615.61it/s]

  0%|          | 196/44898 [00:00<01:03, 698.73it/s]

  1%|          | 271/44898 [00:00<01:02, 716.09it/s]

  1%|          | 343/44898 [00:00<01:05, 684.45it/s]

  1%|          | 412/44898 [00:00<01:05, 679.32it/s]

  1%|          | 481/44898 [00:00<01:08, 652.02it/s]

  1%|          | 547/44898 [00:00<01:08, 649.52it/s]

  1%|▏         | 620/44898 [00:00<01:05, 671.06it/s]

  2%|▏         | 688/44898 [00:01<01:07, 650.19it/s]

  2%|▏         | 754/44898 [00:01<01:12, 608.28it/s]

  2%|▏         | 816/44898 [00:01<01:15, 584.75it/s]

  2%|▏         | 893/44898 [00:01<01:09, 635.88it/s]

  2%|▏         | 967/44898 [00:01<01:06, 665.05it/s]

  2%|▏         | 1042/44898 [00:01<01:04, 681.48it/s]

  2%|▏         | 1111/44898 [00:01<01:04, 675.60it/s]

  3%|▎         | 1187/44898 [00:01<01:02, 697.26it/s]

  3%|▎         | 1258/44898 [00:01<01:04, 676.66it/s]

  3%|▎         | 1326/44898 [00:02<01:10, 614.82it/s]

  3%|▎         | 1389/44898 [00:02<01:12, 599.77it/s]

  3%|▎         | 1460/44898 [00:02<01:09, 628.02it/s]

  3%|▎         | 1534/44898 [00:02<01:06, 656.84it/s]

  4%|▎         | 1614/44898 [00:02<01:02, 692.51it/s]

  4%|▍         | 1704/44898 [00:02<00:57, 748.35it/s]

  4%|▍         | 1780/44898 [00:02<01:04, 663.56it/s]

  4%|▍         | 1855/44898 [00:02<01:03, 676.57it/s]

  4%|▍         | 1925/44898 [00:02<01:04, 663.26it/s]

  4%|▍         | 1998/44898 [00:03<01:03, 677.96it/s]

  5%|▍         | 2068/44898 [00:03<01:03, 677.57it/s]

  5%|▍         | 2138/44898 [00:03<01:02, 681.43it/s]

  5%|▍         | 2216/44898 [00:03<01:00, 708.65it/s]

  5%|▌         | 2288/44898 [00:03<01:03, 668.51it/s]

  5%|▌         | 2356/44898 [00:03<01:10, 606.55it/s]

  5%|▌         | 2421/44898 [00:03<01:09, 615.40it/s]

  6%|▌         | 2484/44898 [00:03<01:08, 617.78it/s]

  6%|▌         | 2547/44898 [00:03<01:12, 585.85it/s]

  6%|▌         | 2629/44898 [00:04<01:05, 650.03it/s]

  6%|▌         | 2701/44898 [00:04<01:03, 668.41it/s]

  6%|▌         | 2773/44898 [00:04<01:01, 681.79it/s]

  6%|▋         | 2842/44898 [00:04<01:04, 650.84it/s]

  7%|▋         | 2920/44898 [00:04<01:01, 684.99it/s]

  7%|▋         | 2990/44898 [00:04<01:02, 670.07it/s]

  7%|▋         | 3069/44898 [00:04<00:59, 701.66it/s]

  7%|▋         | 3140/44898 [00:04<00:59, 697.49it/s]

  7%|▋         | 3211/44898 [00:04<01:01, 675.05it/s]

  7%|▋         | 3284/44898 [00:04<01:00, 689.40it/s]

  7%|▋         | 3361/44898 [00:05<00:58, 712.66it/s]

  8%|▊         | 3442/44898 [00:05<00:55, 740.68it/s]

  8%|▊         | 3517/44898 [00:05<00:56, 738.37it/s]

  8%|▊         | 3593/44898 [00:05<00:55, 742.10it/s]

  8%|▊         | 3668/44898 [00:05<00:56, 726.30it/s]

  8%|▊         | 3741/44898 [00:05<01:00, 680.86it/s]

  8%|▊         | 3810/44898 [00:05<01:03, 648.44it/s]

  9%|▊         | 3876/44898 [00:05<01:10, 583.58it/s]

  9%|▉         | 3959/44898 [00:05<01:03, 647.80it/s]

  9%|▉         | 4027/44898 [00:06<01:02, 655.19it/s]

  9%|▉         | 4094/44898 [00:06<01:02, 657.22it/s]

  9%|▉         | 4167/44898 [00:06<01:00, 677.58it/s]

  9%|▉         | 4247/44898 [00:06<00:57, 710.39it/s]

 10%|▉         | 4319/44898 [00:06<00:57, 703.40it/s]

 10%|▉         | 4394/44898 [00:06<00:56, 715.80it/s]

 10%|▉         | 4472/44898 [00:06<00:55, 732.50it/s]

 10%|█         | 4546/44898 [00:06<00:57, 707.34it/s]

 10%|█         | 4618/44898 [00:06<01:00, 669.46it/s]

 10%|█         | 4696/44898 [00:07<00:57, 700.02it/s]

 11%|█         | 4770/44898 [00:07<00:56, 711.27it/s]

 11%|█         | 4848/44898 [00:07<00:54, 730.61it/s]

 11%|█         | 4922/44898 [00:07<00:55, 722.31it/s]

 11%|█         | 4995/44898 [00:07<00:55, 721.50it/s]

 11%|█▏        | 5071/44898 [00:07<00:54, 732.05it/s]

 11%|█▏        | 5145/44898 [00:07<00:54, 729.64it/s]

 12%|█▏        | 5228/44898 [00:07<00:52, 758.22it/s]

 12%|█▏        | 5304/44898 [00:07<00:54, 729.70it/s]

 12%|█▏        | 5388/44898 [00:07<00:51, 760.94it/s]

 12%|█▏        | 5468/44898 [00:08<00:51, 772.25it/s]

 12%|█▏        | 5547/44898 [00:08<00:50, 776.54it/s]

 13%|█▎        | 5625/44898 [00:08<00:51, 763.54it/s]

 13%|█▎        | 5702/44898 [00:08<00:53, 728.20it/s]

 13%|█▎        | 5776/44898 [00:08<00:54, 721.11it/s]

 13%|█▎        | 5849/44898 [00:08<00:55, 707.78it/s]

 13%|█▎        | 5920/44898 [00:08<00:56, 691.83it/s]

 13%|█▎        | 5990/44898 [00:08<01:01, 634.87it/s]

 13%|█▎        | 6055/44898 [00:08<01:03, 610.32it/s]

 14%|█▎        | 6127/44898 [00:09<01:00, 637.69it/s]

 14%|█▍        | 6192/44898 [00:09<01:00, 639.34it/s]

 14%|█▍        | 6270/44898 [00:09<00:56, 678.12it/s]

 14%|█▍        | 6344/44898 [00:09<00:55, 694.97it/s]

 14%|█▍        | 6414/44898 [00:09<00:55, 694.44it/s]

 14%|█▍        | 6484/44898 [00:09<00:55, 690.52it/s]

 15%|█▍        | 6560/44898 [00:09<00:53, 710.91it/s]

 15%|█▍        | 6632/44898 [00:09<00:53, 709.62it/s]

 15%|█▍        | 6705/44898 [00:09<00:53, 713.73it/s]

 15%|█▌        | 6777/44898 [00:09<00:53, 713.21it/s]

 15%|█▌        | 6854/44898 [00:10<00:52, 729.43it/s]

 15%|█▌        | 6928/44898 [00:10<00:51, 730.82it/s]

 16%|█▌        | 7013/44898 [00:10<00:49, 764.01it/s]

 16%|█▌        | 7091/44898 [00:10<00:49, 767.50it/s]

 16%|█▌        | 7168/44898 [00:10<00:51, 727.06it/s]

 16%|█▌        | 7245/44898 [00:10<00:51, 737.09it/s]

 16%|█▋        | 7320/44898 [00:10<00:52, 715.08it/s]

 16%|█▋        | 7392/44898 [00:10<00:53, 704.17it/s]

 17%|█▋        | 7467/44898 [00:10<00:52, 717.22it/s]

 17%|█▋        | 7544/44898 [00:10<00:51, 731.30it/s]

 17%|█▋        | 7619/44898 [00:11<00:50, 731.62it/s]

 17%|█▋        | 7695/44898 [00:11<00:50, 739.45it/s]

 17%|█▋        | 7770/44898 [00:11<00:52, 708.04it/s]

 17%|█▋        | 7842/44898 [00:11<00:54, 674.02it/s]

 18%|█▊        | 7914/44898 [00:11<00:53, 685.20it/s]

 18%|█▊        | 7983/44898 [00:11<00:55, 662.73it/s]

 18%|█▊        | 8058/44898 [00:11<00:53, 683.84it/s]

 18%|█▊        | 8127/44898 [00:11<01:00, 606.70it/s]

 18%|█▊        | 8201/44898 [00:11<00:57, 640.28it/s]

 18%|█▊        | 8267/44898 [00:12<00:59, 616.40it/s]

 19%|█▊        | 8343/44898 [00:12<00:55, 655.24it/s]

 19%|█▊        | 8410/44898 [00:12<00:55, 658.03it/s]

 19%|█▉        | 8477/44898 [00:12<00:58, 621.04it/s]

 19%|█▉        | 8561/44898 [00:12<00:53, 678.55it/s]

 19%|█▉        | 8630/44898 [00:12<00:53, 675.67it/s]

 19%|█▉        | 8701/44898 [00:12<00:52, 683.84it/s]

 20%|█▉        | 8781/44898 [00:12<00:50, 717.26it/s]

 20%|█▉        | 8854/44898 [00:12<00:51, 702.18it/s]

 20%|█▉        | 8927/44898 [00:13<00:50, 708.60it/s]

 20%|██        | 9014/44898 [00:13<00:47, 755.60it/s]

 20%|██        | 9090/44898 [00:13<00:49, 728.79it/s]

 20%|██        | 9164/44898 [00:13<00:49, 727.22it/s]

 21%|██        | 9241/44898 [00:13<00:48, 737.39it/s]

 21%|██        | 9315/44898 [00:13<00:48, 734.98it/s]

 21%|██        | 9389/44898 [00:13<00:48, 734.10it/s]

 21%|██        | 9463/44898 [00:13<00:49, 712.35it/s]

 21%|██▏       | 9551/44898 [00:13<00:46, 759.20it/s]

 21%|██▏       | 9628/44898 [00:13<00:48, 729.11it/s]

 22%|██▏       | 9702/44898 [00:14<00:50, 702.78it/s]

 22%|██▏       | 9773/44898 [00:14<00:51, 686.95it/s]

 22%|██▏       | 9845/44898 [00:14<00:50, 694.89it/s]

 22%|██▏       | 9923/44898 [00:14<00:48, 717.27it/s]

 22%|██▏       | 9995/44898 [00:14<00:50, 684.68it/s]

 22%|██▏       | 10064/44898 [00:14<00:54, 635.19it/s]

 23%|██▎       | 10140/44898 [00:14<00:51, 668.51it/s]

 23%|██▎       | 10218/44898 [00:14<00:49, 697.44it/s]

 23%|██▎       | 10291/44898 [00:14<00:49, 704.69it/s]

 23%|██▎       | 10363/44898 [00:15<00:49, 700.44it/s]

 23%|██▎       | 10434/44898 [00:15<00:50, 680.26it/s]

 23%|██▎       | 10503/44898 [00:15<00:50, 675.10it/s]

 24%|██▎       | 10591/44898 [00:15<00:46, 732.52it/s]

 24%|██▍       | 10666/44898 [00:15<00:46, 734.84it/s]

 24%|██▍       | 10741/44898 [00:15<00:46, 736.86it/s]

 24%|██▍       | 10815/44898 [00:15<00:46, 730.53it/s]

 24%|██▍       | 10901/44898 [00:15<00:44, 765.18it/s]

 24%|██▍       | 10978/44898 [00:15<00:50, 676.28it/s]

 25%|██▍       | 11052/44898 [00:16<00:48, 692.32it/s]

 25%|██▍       | 11123/44898 [00:16<00:50, 666.63it/s]

 25%|██▍       | 11202/44898 [00:16<00:48, 697.61it/s]

 25%|██▌       | 11273/44898 [00:16<00:49, 680.30it/s]

 25%|██▌       | 11342/44898 [00:16<00:50, 665.65it/s]

 25%|██▌       | 11418/44898 [00:16<00:48, 689.18it/s]

 26%|██▌       | 11488/44898 [00:16<00:48, 681.86it/s]

 26%|██▌       | 11557/44898 [00:16<00:49, 680.10it/s]

 26%|██▌       | 11631/44898 [00:16<00:47, 694.77it/s]

 26%|██▌       | 11704/44898 [00:16<00:47, 704.59it/s]

 26%|██▌       | 11775/44898 [00:17<00:48, 682.75it/s]

 26%|██▋       | 11844/44898 [00:17<00:48, 678.24it/s]

 27%|██▋       | 11914/44898 [00:17<00:48, 683.72it/s]

 27%|██▋       | 11983/44898 [00:17<00:50, 655.55it/s]

 27%|██▋       | 12050/44898 [00:17<00:49, 659.03it/s]

 27%|██▋       | 12130/44898 [00:17<00:46, 697.52it/s]

 27%|██▋       | 12201/44898 [00:17<00:47, 686.09it/s]

 27%|██▋       | 12270/44898 [00:17<00:49, 663.11it/s]

 28%|██▊       | 12352/44898 [00:17<00:46, 707.18it/s]

 28%|██▊       | 12424/44898 [00:18<00:46, 697.56it/s]

 28%|██▊       | 12502/44898 [00:18<00:45, 717.67it/s]

 28%|██▊       | 12575/44898 [00:18<00:46, 698.54it/s]

 28%|██▊       | 12646/44898 [00:18<00:46, 689.28it/s]

 28%|██▊       | 12718/44898 [00:18<00:46, 691.47it/s]

 28%|██▊       | 12788/44898 [00:18<00:46, 683.28it/s]

 29%|██▊       | 12858/44898 [00:18<00:46, 688.03it/s]

 29%|██▉       | 12941/44898 [00:18<00:44, 724.47it/s]

 29%|██▉       | 13021/44898 [00:18<00:43, 738.13it/s]

 29%|██▉       | 13095/44898 [00:18<00:44, 718.57it/s]

 29%|██▉       | 13167/44898 [00:19<00:45, 697.20it/s]

 29%|██▉       | 13237/44898 [00:19<00:46, 685.00it/s]

 30%|██▉       | 13306/44898 [00:19<00:46, 680.62it/s]

 30%|██▉       | 13375/44898 [00:19<00:46, 675.83it/s]

 30%|██▉       | 13443/44898 [00:19<00:48, 655.12it/s]

 30%|███       | 13513/44898 [00:19<00:47, 666.48it/s]

 30%|███       | 13594/44898 [00:19<00:44, 704.18it/s]

 30%|███       | 13667/44898 [00:19<00:44, 708.85it/s]

 31%|███       | 13739/44898 [00:19<00:45, 683.56it/s]

 31%|███       | 13813/44898 [00:20<00:44, 699.40it/s]

 31%|███       | 13885/44898 [00:20<00:44, 704.02it/s]

 31%|███       | 13958/44898 [00:20<00:43, 707.96it/s]

 31%|███▏      | 14034/44898 [00:20<00:42, 723.11it/s]

 31%|███▏      | 14110/44898 [00:20<00:42, 731.29it/s]

 32%|███▏      | 14184/44898 [00:20<00:43, 708.27it/s]

 32%|███▏      | 14257/44898 [00:20<00:42, 713.14it/s]

 32%|███▏      | 14330/44898 [00:20<00:42, 713.97it/s]

 32%|███▏      | 14402/44898 [00:20<00:44, 686.86it/s]

 32%|███▏      | 14479/44898 [00:20<00:42, 708.70it/s]

 32%|███▏      | 14551/44898 [00:21<00:42, 710.66it/s]

 33%|███▎      | 14623/44898 [00:21<00:43, 689.69it/s]

 33%|███▎      | 14693/44898 [00:21<00:46, 652.08it/s]

 33%|███▎      | 14759/44898 [00:21<00:50, 600.32it/s]

 33%|███▎      | 14834/44898 [00:21<00:47, 638.31it/s]

 33%|███▎      | 14899/44898 [00:21<00:52, 571.06it/s]

 33%|███▎      | 14972/44898 [00:21<00:48, 611.74it/s]

 34%|███▎      | 15058/44898 [00:21<00:44, 676.99it/s]

 34%|███▎      | 15128/44898 [00:21<00:44, 668.08it/s]

 34%|███▍      | 15203/44898 [00:22<00:43, 686.94it/s]

 34%|███▍      | 15276/44898 [00:22<00:42, 696.00it/s]

 34%|███▍      | 15347/44898 [00:22<00:43, 686.08it/s]

 34%|███▍      | 15417/44898 [00:22<00:42, 688.48it/s]

 35%|███▍      | 15495/44898 [00:22<00:41, 710.77it/s]

 35%|███▍      | 15567/44898 [00:22<00:41, 701.97it/s]

 35%|███▍      | 15644/44898 [00:22<00:40, 717.31it/s]

 35%|███▌      | 15718/44898 [00:22<00:40, 721.10it/s]

 35%|███▌      | 15798/44898 [00:22<00:39, 733.90it/s]

 35%|███▌      | 15872/44898 [00:23<00:43, 660.03it/s]

 36%|███▌      | 15953/44898 [00:23<00:41, 698.92it/s]

 36%|███▌      | 16038/44898 [00:23<00:38, 740.80it/s]

 36%|███▌      | 16114/44898 [00:23<00:40, 719.07it/s]

 36%|███▌      | 16187/44898 [00:23<00:41, 691.99it/s]

 36%|███▌      | 16268/44898 [00:23<00:39, 724.67it/s]

 36%|███▋      | 16342/44898 [00:23<00:39, 727.81it/s]

 37%|███▋      | 16416/44898 [00:23<00:39, 721.20it/s]

 37%|███▋      | 16489/44898 [00:23<00:41, 686.43it/s]

 37%|███▋      | 16559/44898 [00:24<00:41, 684.82it/s]

 37%|███▋      | 16640/44898 [00:24<00:39, 716.17it/s]

 37%|███▋      | 16712/44898 [00:24<00:41, 682.54it/s]

 37%|███▋      | 16781/44898 [00:24<00:41, 683.04it/s]

 38%|███▊      | 16854/44898 [00:24<00:40, 695.79it/s]

 38%|███▊      | 16924/44898 [00:24<00:43, 637.87it/s]

 38%|███▊      | 16996/44898 [00:24<00:42, 659.76it/s]

 38%|███▊      | 17065/44898 [00:24<00:41, 666.36it/s]

 38%|███▊      | 17140/44898 [00:24<00:40, 686.49it/s]

 38%|███▊      | 17210/44898 [00:24<00:40, 684.69it/s]

 38%|███▊      | 17279/44898 [00:25<00:41, 664.79it/s]

 39%|███▊      | 17356/44898 [00:25<00:39, 692.51it/s]

 39%|███▉      | 17426/44898 [00:25<00:40, 681.22it/s]

 39%|███▉      | 17495/44898 [00:25<00:40, 682.15it/s]

 39%|███▉      | 17566/44898 [00:25<00:39, 688.50it/s]

 39%|███▉      | 17649/44898 [00:25<00:37, 729.29it/s]

 39%|███▉      | 17726/44898 [00:25<00:36, 739.75it/s]

 40%|███▉      | 17801/44898 [00:25<00:38, 710.20it/s]

 40%|███▉      | 17873/44898 [00:25<00:39, 681.86it/s]

 40%|███▉      | 17946/44898 [00:26<00:38, 691.83it/s]

 40%|████      | 18020/44898 [00:26<00:38, 702.93it/s]

 40%|████      | 18091/44898 [00:26<00:41, 643.77it/s]

 40%|████      | 18173/44898 [00:26<00:38, 692.02it/s]

 41%|████      | 18244/44898 [00:26<00:40, 666.21it/s]

 41%|████      | 18313/44898 [00:26<00:39, 669.17it/s]

 41%|████      | 18386/44898 [00:26<00:38, 682.65it/s]

 41%|████      | 18472/44898 [00:26<00:36, 732.59it/s]

 41%|████▏     | 18546/44898 [00:26<00:35, 733.35it/s]

 41%|████▏     | 18625/44898 [00:26<00:35, 747.35it/s]

 42%|████▏     | 18701/44898 [00:27<00:35, 739.45it/s]

 42%|████▏     | 18776/44898 [00:27<00:35, 733.91it/s]

 42%|████▏     | 18854/44898 [00:27<00:34, 744.13it/s]

 42%|████▏     | 18929/44898 [00:27<00:35, 722.68it/s]

 42%|████▏     | 19002/44898 [00:27<00:36, 718.27it/s]

 42%|████▏     | 19074/44898 [00:27<00:36, 702.84it/s]

 43%|████▎     | 19151/44898 [00:27<00:35, 722.17it/s]

 43%|████▎     | 19224/44898 [00:27<00:35, 722.42it/s]

 43%|████▎     | 19297/44898 [00:27<00:36, 707.15it/s]

 43%|████▎     | 19374/44898 [00:28<00:35, 722.83it/s]

 43%|████▎     | 19448/44898 [00:28<00:35, 725.78it/s]

 43%|████▎     | 19530/44898 [00:28<00:33, 751.01it/s]

 44%|████▎     | 19606/44898 [00:28<00:34, 743.37it/s]

 44%|████▍     | 19684/44898 [00:28<00:33, 753.56it/s]

 44%|████▍     | 19760/44898 [00:28<00:35, 706.09it/s]

 44%|████▍     | 19832/44898 [00:28<00:37, 675.68it/s]

 44%|████▍     | 19902/44898 [00:28<00:36, 680.62it/s]

 44%|████▍     | 19979/44898 [00:28<00:35, 705.49it/s]

 45%|████▍     | 20060/44898 [00:28<00:33, 733.00it/s]

 45%|████▍     | 20139/44898 [00:29<00:33, 748.29it/s]

 45%|████▌     | 20215/44898 [00:29<00:33, 736.11it/s]

 45%|████▌     | 20294/44898 [00:29<00:32, 751.43it/s]

 45%|████▌     | 20372/44898 [00:29<00:32, 755.28it/s]

 46%|████▌     | 20449/44898 [00:29<00:32, 757.02it/s]

 46%|████▌     | 20525/44898 [00:29<00:32, 751.22it/s]

 46%|████▌     | 20601/44898 [00:29<00:35, 687.46it/s]

 46%|████▌     | 20671/44898 [00:29<00:36, 670.31it/s]

 46%|████▌     | 20756/44898 [00:29<00:33, 717.54it/s]

 46%|████▋     | 20835/44898 [00:30<00:32, 736.78it/s]

 47%|████▋     | 20910/44898 [00:30<00:33, 717.22it/s]

 47%|████▋     | 20983/44898 [00:30<00:34, 683.56it/s]

 47%|████▋     | 21052/44898 [00:30<00:35, 674.24it/s]

 47%|████▋     | 21126/44898 [00:30<00:34, 691.87it/s]

 47%|████▋     | 21206/44898 [00:30<00:32, 722.41it/s]

 47%|████▋     | 21279/44898 [00:30<00:33, 711.08it/s]

 48%|████▊     | 21354/44898 [00:30<00:32, 719.45it/s]

 48%|████▊     | 21427/44898 [00:30<00:33, 706.42it/s]

 48%|████▊     | 21508/44898 [00:31<00:31, 733.27it/s]

 48%|████▊     | 21582/44898 [00:31<00:31, 733.17it/s]

 48%|████▊     | 21656/44898 [00:31<00:33, 691.39it/s]

 48%|████▊     | 21727/44898 [00:31<00:33, 694.16it/s]

 49%|████▊     | 21801/44898 [00:31<00:32, 707.12it/s]

 49%|████▊     | 21873/44898 [00:31<00:35, 648.54it/s]

 49%|████▉     | 21953/44898 [00:31<00:33, 689.06it/s]

 49%|████▉     | 22024/44898 [00:31<00:34, 667.31it/s]

 49%|████▉     | 22093/44898 [00:31<00:34, 669.22it/s]

 49%|████▉     | 22165/44898 [00:31<00:33, 676.73it/s]

 50%|████▉     | 22243/44898 [00:32<00:32, 704.97it/s]

 50%|████▉     | 22314/44898 [00:32<00:34, 661.79it/s]

 50%|████▉     | 22394/44898 [00:32<00:32, 699.07it/s]

 50%|█████     | 22470/44898 [00:32<00:31, 715.45it/s]

 50%|█████     | 22547/44898 [00:32<00:30, 730.50it/s]

 50%|█████     | 22621/44898 [00:32<00:33, 659.86it/s]

 51%|█████     | 22693/44898 [00:32<00:32, 674.83it/s]

 51%|█████     | 22762/44898 [00:32<00:32, 676.65it/s]

 51%|█████     | 22831/44898 [00:32<00:32, 676.58it/s]

 51%|█████     | 22900/44898 [00:33<00:34, 630.60it/s]

 51%|█████     | 22974/44898 [00:33<00:33, 657.59it/s]

 51%|█████▏    | 23046/44898 [00:33<00:32, 673.90it/s]

 51%|█████▏    | 23115/44898 [00:33<00:32, 670.98it/s]

 52%|█████▏    | 23187/44898 [00:33<00:31, 682.76it/s]

 52%|█████▏    | 23256/44898 [00:33<00:32, 657.69it/s]

 52%|█████▏    | 23325/44898 [00:33<00:32, 665.11it/s]

 52%|█████▏    | 23405/44898 [00:33<00:30, 704.07it/s]

 52%|█████▏    | 23485/44898 [00:33<00:29, 729.54it/s]

 52%|█████▏    | 23559/44898 [00:34<00:31, 682.52it/s]

 53%|█████▎    | 23629/44898 [00:34<00:32, 652.94it/s]

 53%|█████▎    | 23704/44898 [00:34<00:31, 677.00it/s]

 53%|█████▎    | 23773/44898 [00:34<00:33, 639.30it/s]

 53%|█████▎    | 23854/44898 [00:34<00:30, 681.59it/s]

 53%|█████▎    | 23926/44898 [00:34<00:30, 690.70it/s]

 53%|█████▎    | 24009/44898 [00:34<00:28, 729.91it/s]

 54%|█████▎    | 24086/44898 [00:34<00:28, 731.06it/s]

 54%|█████▍    | 24160/44898 [00:34<00:28, 716.92it/s]

 54%|█████▍    | 24233/44898 [00:34<00:28, 715.91it/s]

 54%|█████▍    | 24309/44898 [00:35<00:28, 728.26it/s]

 54%|█████▍    | 24383/44898 [00:35<00:28, 721.82it/s]

 54%|█████▍    | 24456/44898 [00:35<00:28, 721.47it/s]

 55%|█████▍    | 24529/44898 [00:35<00:28, 715.47it/s]

 55%|█████▍    | 24601/44898 [00:35<00:28, 701.99it/s]

 55%|█████▍    | 24680/44898 [00:35<00:27, 724.70it/s]

 55%|█████▌    | 24760/44898 [00:35<00:27, 739.82it/s]

 55%|█████▌    | 24840/44898 [00:35<00:26, 756.04it/s]

 56%|█████▌    | 24924/44898 [00:35<00:25, 779.38it/s]

 56%|█████▌    | 25003/44898 [00:36<00:25, 778.97it/s]

 56%|█████▌    | 25081/44898 [00:36<00:26, 760.74it/s]

 56%|█████▌    | 25158/44898 [00:36<00:27, 713.69it/s]

 56%|█████▌    | 25234/44898 [00:36<00:27, 724.52it/s]

 56%|█████▋    | 25307/44898 [00:36<00:28, 698.71it/s]

 57%|█████▋    | 25378/44898 [00:36<00:28, 682.15it/s]

 57%|█████▋    | 25455/44898 [00:36<00:27, 705.58it/s]

 57%|█████▋    | 25526/44898 [00:36<00:28, 678.97it/s]

 57%|█████▋    | 25595/44898 [00:36<00:28, 667.44it/s]

 57%|█████▋    | 25667/44898 [00:36<00:28, 680.67it/s]

 57%|█████▋    | 25748/44898 [00:37<00:26, 716.69it/s]

 58%|█████▊    | 25821/44898 [00:37<00:26, 719.80it/s]

 58%|█████▊    | 25902/44898 [00:37<00:25, 743.28it/s]

 58%|█████▊    | 25977/44898 [00:37<00:25, 738.43it/s]

 58%|█████▊    | 26051/44898 [00:37<00:26, 721.06it/s]

 58%|█████▊    | 26132/44898 [00:37<00:25, 744.75it/s]

 58%|█████▊    | 26207/44898 [00:37<00:25, 742.62it/s]

 59%|█████▊    | 26282/44898 [00:37<00:26, 695.91it/s]

 59%|█████▊    | 26353/44898 [00:37<00:26, 696.79it/s]

 59%|█████▉    | 26425/44898 [00:38<00:26, 701.90it/s]

 59%|█████▉    | 26498/44898 [00:38<00:26, 705.92it/s]

 59%|█████▉    | 26569/44898 [00:38<00:26, 681.91it/s]

 59%|█████▉    | 26638/44898 [00:38<00:28, 642.59it/s]

 60%|█████▉    | 26715/44898 [00:38<00:26, 677.38it/s]

 60%|█████▉    | 26784/44898 [00:38<00:26, 678.84it/s]

 60%|█████▉    | 26864/44898 [00:38<00:25, 711.91it/s]

 60%|█████▉    | 26937/44898 [00:38<00:25, 715.88it/s]

 60%|██████    | 27012/44898 [00:38<00:24, 725.83it/s]

 60%|██████    | 27089/44898 [00:38<00:24, 735.16it/s]

 61%|██████    | 27176/44898 [00:39<00:22, 773.37it/s]

 61%|██████    | 27262/44898 [00:39<00:22, 798.77it/s]

 61%|██████    | 27343/44898 [00:39<00:22, 784.12it/s]

 61%|██████    | 27422/44898 [00:39<00:24, 722.45it/s]

 61%|██████    | 27496/44898 [00:39<00:24, 718.37it/s]

 61%|██████▏   | 27572/44898 [00:39<00:23, 729.18it/s]

 62%|██████▏   | 27646/44898 [00:39<00:25, 687.25it/s]

 62%|██████▏   | 27731/44898 [00:39<00:23, 731.44it/s]

 62%|██████▏   | 27810/44898 [00:39<00:22, 747.39it/s]

 62%|██████▏   | 27886/44898 [00:40<00:23, 720.01it/s]

 62%|██████▏   | 27959/44898 [00:40<00:23, 720.56it/s]

 62%|██████▏   | 28039/44898 [00:40<00:22, 737.78it/s]

 63%|██████▎   | 28114/44898 [00:40<00:22, 735.91it/s]

 63%|██████▎   | 28188/44898 [00:40<00:22, 736.08it/s]

 63%|██████▎   | 28262/44898 [00:40<00:22, 724.94it/s]

 63%|██████▎   | 28337/44898 [00:40<00:22, 729.16it/s]

 63%|██████▎   | 28411/44898 [00:40<00:23, 696.35it/s]

 63%|██████▎   | 28481/44898 [00:40<00:24, 658.91it/s]

 64%|██████▎   | 28550/44898 [00:41<00:24, 663.45it/s]

 64%|██████▍   | 28630/44898 [00:41<00:23, 700.99it/s]

 64%|██████▍   | 28713/44898 [00:41<00:22, 735.30it/s]

 64%|██████▍   | 28787/44898 [00:41<00:21, 732.60it/s]

 64%|██████▍   | 28868/44898 [00:41<00:21, 753.81it/s]

 64%|██████▍   | 28946/44898 [00:41<00:21, 759.22it/s]

 65%|██████▍   | 29023/44898 [00:41<00:21, 754.01it/s]

 65%|██████▍   | 29099/44898 [00:41<00:21, 752.16it/s]

 65%|██████▍   | 29183/44898 [00:41<00:20, 776.70it/s]

 65%|██████▌   | 29261/44898 [00:41<00:20, 755.78it/s]

 65%|██████▌   | 29337/44898 [00:42<00:21, 709.59it/s]

 66%|██████▌   | 29409/44898 [00:42<00:22, 674.65it/s]

 66%|██████▌   | 29492/44898 [00:42<00:21, 712.95it/s]

 66%|██████▌   | 29567/44898 [00:42<00:21, 723.30it/s]

 66%|██████▌   | 29640/44898 [00:42<00:21, 719.00it/s]

 66%|██████▌   | 29714/44898 [00:42<00:20, 724.03it/s]

 66%|██████▋   | 29789/44898 [00:42<00:20, 730.54it/s]

 67%|██████▋   | 29863/44898 [00:42<00:22, 671.25it/s]

 67%|██████▋   | 29932/44898 [00:42<00:23, 650.47it/s]

 67%|██████▋   | 30023/44898 [00:43<00:20, 717.63it/s]

 67%|██████▋   | 30100/44898 [00:43<00:20, 731.65it/s]

 67%|██████▋   | 30176/44898 [00:43<00:19, 739.33it/s]

 67%|██████▋   | 30251/44898 [00:43<00:20, 716.22it/s]

 68%|██████▊   | 30327/44898 [00:43<00:20, 726.99it/s]

 68%|██████▊   | 30401/44898 [00:43<00:20, 696.79it/s]

 68%|██████▊   | 30476/44898 [00:43<00:20, 709.98it/s]

 68%|██████▊   | 30548/44898 [00:43<00:21, 655.37it/s]

 68%|██████▊   | 30619/44898 [00:43<00:21, 667.38it/s]

 68%|██████▊   | 30694/44898 [00:43<00:20, 690.09it/s]

 69%|██████▊   | 30764/44898 [00:44<00:20, 677.31it/s]

 69%|██████▊   | 30833/44898 [00:44<00:21, 657.18it/s]

 69%|██████▉   | 30909/44898 [00:44<00:20, 685.56it/s]

 69%|██████▉   | 30980/44898 [00:44<00:20, 689.76it/s]

 69%|██████▉   | 31050/44898 [00:44<00:20, 690.57it/s]

 69%|██████▉   | 31136/44898 [00:44<00:18, 735.99it/s]

 70%|██████▉   | 31218/44898 [00:44<00:18, 757.88it/s]

 70%|██████▉   | 31294/44898 [00:44<00:18, 748.73it/s]

 70%|██████▉   | 31370/44898 [00:44<00:19, 697.53it/s]

 70%|███████   | 31452/44898 [00:45<00:18, 730.52it/s]

 70%|███████   | 31526/44898 [00:45<00:19, 682.66it/s]

 70%|███████   | 31596/44898 [00:45<00:20, 637.60it/s]

 71%|███████   | 31666/44898 [00:45<00:20, 652.69it/s]

 71%|███████   | 31736/44898 [00:45<00:19, 665.05it/s]

 71%|███████   | 31812/44898 [00:45<00:18, 691.02it/s]

 71%|███████   | 31883/44898 [00:45<00:18, 695.40it/s]

 71%|███████   | 31954/44898 [00:45<00:18, 694.43it/s]

 71%|███████▏  | 32040/44898 [00:45<00:17, 738.91it/s]

 72%|███████▏  | 32120/44898 [00:46<00:16, 754.71it/s]

 72%|███████▏  | 32211/44898 [00:46<00:15, 799.27it/s]

 72%|███████▏  | 32296/44898 [00:46<00:15, 811.84it/s]

 72%|███████▏  | 32378/44898 [00:46<00:16, 744.02it/s]

 72%|███████▏  | 32454/44898 [00:46<00:18, 682.30it/s]

 72%|███████▏  | 32524/44898 [00:46<00:18, 671.08it/s]

 73%|███████▎  | 32596/44898 [00:46<00:18, 679.11it/s]

 73%|███████▎  | 32681/44898 [00:46<00:16, 725.95it/s]

 73%|███████▎  | 32755/44898 [00:46<00:17, 712.30it/s]

 73%|███████▎  | 32844/44898 [00:47<00:15, 760.77it/s]

 73%|███████▎  | 32921/44898 [00:47<00:17, 685.43it/s]

 73%|███████▎  | 32999/44898 [00:47<00:16, 710.45it/s]

 74%|███████▎  | 33072/44898 [00:47<00:16, 705.19it/s]

 74%|███████▍  | 33159/44898 [00:47<00:15, 747.60it/s]

 74%|███████▍  | 33235/44898 [00:47<00:15, 740.18it/s]

 74%|███████▍  | 33310/44898 [00:47<00:16, 717.46it/s]

 74%|███████▍  | 33383/44898 [00:47<00:16, 684.05it/s]

 75%|███████▍  | 33462/44898 [00:47<00:16, 713.19it/s]

 75%|███████▍  | 33534/44898 [00:47<00:16, 705.88it/s]

 75%|███████▍  | 33606/44898 [00:48<00:16, 694.83it/s]

 75%|███████▌  | 33676/44898 [00:48<00:18, 605.53it/s]

 75%|███████▌  | 33742/44898 [00:48<00:18, 619.10it/s]

 75%|███████▌  | 33822/44898 [00:48<00:16, 666.35it/s]

 76%|███████▌  | 33903/44898 [00:48<00:15, 703.12it/s]

 76%|███████▌  | 33975/44898 [00:48<00:15, 691.47it/s]

 76%|███████▌  | 34052/44898 [00:48<00:15, 712.39it/s]

 76%|███████▌  | 34125/44898 [00:48<00:15, 712.37it/s]

 76%|███████▌  | 34202/44898 [00:48<00:14, 728.23it/s]

 76%|███████▋  | 34289/44898 [00:49<00:13, 766.41it/s]

 77%|███████▋  | 34366/44898 [00:49<00:14, 744.31it/s]

 77%|███████▋  | 34441/44898 [00:49<00:15, 688.81it/s]

 77%|███████▋  | 34524/44898 [00:49<00:14, 727.65it/s]

 77%|███████▋  | 34598/44898 [00:49<00:14, 698.04it/s]

 77%|███████▋  | 34678/44898 [00:49<00:14, 725.59it/s]

 77%|███████▋  | 34752/44898 [00:49<00:14, 681.67it/s]

 78%|███████▊  | 34836/44898 [00:49<00:13, 723.89it/s]

 78%|███████▊  | 34910/44898 [00:49<00:13, 720.84it/s]

 78%|███████▊  | 34983/44898 [00:50<00:14, 688.69it/s]

 78%|███████▊  | 35063/44898 [00:50<00:13, 713.94it/s]

 78%|███████▊  | 35136/44898 [00:50<00:13, 713.64it/s]

 78%|███████▊  | 35208/44898 [00:50<00:14, 682.28it/s]

 79%|███████▊  | 35277/44898 [00:50<00:14, 671.25it/s]

 79%|███████▊  | 35345/44898 [00:50<00:14, 670.38it/s]

 79%|███████▉  | 35428/44898 [00:50<00:13, 715.14it/s]

 79%|███████▉  | 35502/44898 [00:50<00:13, 720.89it/s]

 79%|███████▉  | 35575/44898 [00:50<00:13, 689.65it/s]

 79%|███████▉  | 35657/44898 [00:51<00:12, 725.71it/s]

 80%|███████▉  | 35735/44898 [00:51<00:12, 737.93it/s]

 80%|███████▉  | 35810/44898 [00:51<00:12, 736.69it/s]

 80%|███████▉  | 35890/44898 [00:51<00:11, 753.07it/s]

 80%|████████  | 35966/44898 [00:51<00:12, 728.88it/s]

 80%|████████  | 36040/44898 [00:51<00:12, 721.66it/s]

 80%|████████  | 36113/44898 [00:51<00:12, 715.37it/s]

 81%|████████  | 36196/44898 [00:51<00:11, 746.26it/s]

 81%|████████  | 36271/44898 [00:51<00:12, 691.99it/s]

 81%|████████  | 36342/44898 [00:51<00:12, 691.35it/s]

 81%|████████  | 36413/44898 [00:52<00:12, 696.23it/s]

 81%|████████▏ | 36484/44898 [00:52<00:12, 656.62it/s]

 81%|████████▏ | 36551/44898 [00:52<00:13, 624.98it/s]

 82%|████████▏ | 36628/44898 [00:52<00:12, 664.00it/s]

 82%|████████▏ | 36705/44898 [00:52<00:11, 689.41it/s]

 82%|████████▏ | 36783/44898 [00:52<00:11, 714.61it/s]

 82%|████████▏ | 36863/44898 [00:52<00:10, 738.76it/s]

 82%|████████▏ | 36938/44898 [00:52<00:10, 737.65it/s]

 82%|████████▏ | 37013/44898 [00:52<00:10, 722.11it/s]

 83%|████████▎ | 37089/44898 [00:53<00:10, 731.25it/s]

 83%|████████▎ | 37163/44898 [00:53<00:10, 712.56it/s]

 83%|████████▎ | 37235/44898 [00:53<00:10, 710.33it/s]

 83%|████████▎ | 37310/44898 [00:53<00:10, 721.12it/s]

 83%|████████▎ | 37384/44898 [00:53<00:10, 724.94it/s]

 83%|████████▎ | 37473/44898 [00:53<00:09, 772.54it/s]

 84%|████████▎ | 37551/44898 [00:53<00:09, 768.46it/s]

 84%|████████▍ | 37628/44898 [00:53<00:09, 767.69it/s]

 84%|████████▍ | 37705/44898 [00:53<00:09, 738.50it/s]

 84%|████████▍ | 37780/44898 [00:53<00:09, 739.40it/s]

 84%|████████▍ | 37855/44898 [00:54<00:09, 729.22it/s]

 84%|████████▍ | 37931/44898 [00:54<00:09, 737.87it/s]

 85%|████████▍ | 38005/44898 [00:54<00:09, 724.78it/s]

 85%|████████▍ | 38085/44898 [00:54<00:09, 743.95it/s]

 85%|████████▌ | 38170/44898 [00:54<00:08, 772.66it/s]

 85%|████████▌ | 38248/44898 [00:54<00:08, 770.32it/s]

 85%|████████▌ | 38326/44898 [00:54<00:08, 739.40it/s]

 86%|████████▌ | 38401/44898 [00:54<00:09, 677.47it/s]

 86%|████████▌ | 38470/44898 [00:54<00:09, 665.22it/s]

 86%|████████▌ | 38540/44898 [00:55<00:09, 674.26it/s]

 86%|████████▌ | 38616/44898 [00:55<00:09, 697.46it/s]

 86%|████████▌ | 38697/44898 [00:55<00:08, 729.73it/s]

 86%|████████▋ | 38771/44898 [00:55<00:08, 709.24it/s]

 87%|████████▋ | 38846/44898 [00:55<00:08, 720.64it/s]

 87%|████████▋ | 38919/44898 [00:55<00:08, 723.27it/s]

 87%|████████▋ | 38992/44898 [00:55<00:08, 692.48it/s]

 87%|████████▋ | 39062/44898 [00:55<00:08, 691.28it/s]

 87%|████████▋ | 39132/44898 [00:55<00:08, 655.20it/s]

 87%|████████▋ | 39210/44898 [00:55<00:08, 686.65it/s]

 87%|████████▋ | 39280/44898 [00:56<00:08, 677.03it/s]

 88%|████████▊ | 39360/44898 [00:56<00:07, 710.88it/s]

 88%|████████▊ | 39432/44898 [00:56<00:08, 680.10it/s]

 88%|████████▊ | 39501/44898 [00:56<00:08, 633.34it/s]

 88%|████████▊ | 39575/44898 [00:56<00:08, 660.72it/s]

 88%|████████▊ | 39646/44898 [00:56<00:07, 672.25it/s]

 88%|████████▊ | 39716/44898 [00:56<00:07, 677.24it/s]

 89%|████████▊ | 39785/44898 [00:56<00:07, 669.64it/s]

 89%|████████▉ | 39860/44898 [00:56<00:07, 690.51it/s]

 89%|████████▉ | 39930/44898 [00:57<00:07, 683.25it/s]

 89%|████████▉ | 40003/44898 [00:57<00:07, 692.59it/s]

 89%|████████▉ | 40082/44898 [00:57<00:06, 720.53it/s]

 89%|████████▉ | 40162/44898 [00:57<00:06, 741.43it/s]

 90%|████████▉ | 40237/44898 [00:57<00:06, 743.04it/s]

 90%|████████▉ | 40312/44898 [00:57<00:06, 663.30it/s]

 90%|████████▉ | 40384/44898 [00:57<00:06, 677.89it/s]

 90%|█████████ | 40454/44898 [00:57<00:06, 651.72it/s]

 90%|█████████ | 40534/44898 [00:57<00:06, 691.99it/s]

 90%|█████████ | 40605/44898 [00:58<00:06, 679.47it/s]

 91%|█████████ | 40674/44898 [00:58<00:06, 669.22it/s]

 91%|█████████ | 40751/44898 [00:58<00:05, 697.66it/s]

 91%|█████████ | 40822/44898 [00:58<00:06, 635.78it/s]

 91%|█████████ | 40906/44898 [00:58<00:05, 689.31it/s]

 91%|█████████▏| 40977/44898 [00:58<00:05, 669.68it/s]

 91%|█████████▏| 41046/44898 [00:58<00:05, 664.33it/s]

 92%|█████████▏| 41114/44898 [00:58<00:05, 650.18it/s]

 92%|█████████▏| 41180/44898 [00:58<00:05, 646.08it/s]

 92%|█████████▏| 41253/44898 [00:59<00:05, 664.37it/s]

 92%|█████████▏| 41332/44898 [00:59<00:05, 700.19it/s]

 92%|█████████▏| 41403/44898 [00:59<00:05, 693.81it/s]

 92%|█████████▏| 41473/44898 [00:59<00:05, 682.43it/s]

 93%|█████████▎| 41542/44898 [00:59<00:05, 663.14it/s]

 93%|█████████▎| 41611/44898 [00:59<00:04, 669.57it/s]

 93%|█████████▎| 41682/44898 [00:59<00:04, 678.18it/s]

 93%|█████████▎| 41765/44898 [00:59<00:04, 714.38it/s]

 93%|█████████▎| 41837/44898 [00:59<00:04, 686.56it/s]

 93%|█████████▎| 41912/44898 [00:59<00:04, 701.46it/s]

 94%|█████████▎| 41983/44898 [01:00<00:04, 684.59it/s]

 94%|█████████▎| 42053/44898 [01:00<00:04, 686.75it/s]

 94%|█████████▍| 42128/44898 [01:00<00:03, 698.35it/s]

 94%|█████████▍| 42201/44898 [01:00<00:03, 704.17it/s]

 94%|█████████▍| 42272/44898 [01:00<00:03, 669.13it/s]

 94%|█████████▍| 42340/44898 [01:00<00:03, 655.75it/s]

 94%|█████████▍| 42406/44898 [01:00<00:03, 627.18it/s]

 95%|█████████▍| 42486/44898 [01:00<00:03, 672.45it/s]

 95%|█████████▍| 42556/44898 [01:00<00:03, 679.08it/s]

 95%|█████████▍| 42625/44898 [01:01<00:03, 654.79it/s]

 95%|█████████▌| 42704/44898 [01:01<00:03, 687.03it/s]

 95%|█████████▌| 42782/44898 [01:01<00:02, 710.48it/s]

 95%|█████████▌| 42854/44898 [01:01<00:02, 687.22it/s]

 96%|█████████▌| 42924/44898 [01:01<00:02, 663.22it/s]

 96%|█████████▌| 42991/44898 [01:01<00:03, 616.66it/s]

 96%|█████████▌| 43057/44898 [01:01<00:02, 625.80it/s]

 96%|█████████▌| 43129/44898 [01:01<00:02, 651.79it/s]

 96%|█████████▌| 43203/44898 [01:01<00:02, 674.35it/s]

 96%|█████████▋| 43271/44898 [01:02<00:02, 672.77it/s]

 97%|█████████▋| 43339/44898 [01:02<00:02, 666.14it/s]

 97%|█████████▋| 43412/44898 [01:02<00:02, 683.46it/s]

 97%|█████████▋| 43492/44898 [01:02<00:01, 715.81it/s]

 97%|█████████▋| 43564/44898 [01:02<00:01, 692.19it/s]

 97%|█████████▋| 43634/44898 [01:02<00:01, 670.15it/s]

 97%|█████████▋| 43712/44898 [01:02<00:01, 701.26it/s]

 98%|█████████▊| 43795/44898 [01:02<00:01, 736.57it/s]

 98%|█████████▊| 43870/44898 [01:02<00:01, 725.39it/s]

 98%|█████████▊| 43946/44898 [01:02<00:01, 735.23it/s]

 98%|█████████▊| 44032/44898 [01:03<00:01, 770.51it/s]

 98%|█████████▊| 44116/44898 [01:03<00:00, 786.77it/s]

 98%|█████████▊| 44195/44898 [01:03<00:00, 746.70it/s]

 99%|█████████▊| 44271/44898 [01:03<00:00, 732.91it/s]

 99%|█████████▉| 44345/44898 [01:03<00:00, 716.23it/s]

 99%|█████████▉| 44417/44898 [01:03<00:00, 703.14it/s]

 99%|█████████▉| 44488/44898 [01:03<00:00, 572.83it/s]

 99%|█████████▉| 44555/44898 [01:03<00:00, 594.55it/s]

 99%|█████████▉| 44633/44898 [01:03<00:00, 641.03it/s]

100%|█████████▉| 44701/44898 [01:04<00:00, 650.29it/s]

100%|█████████▉| 44769/44898 [01:04<00:00, 617.14it/s]

100%|█████████▉| 44842/44898 [01:04<00:00, 645.57it/s]

100%|██████████| 44898/44898 [01:04<00:00, 696.27it/s]

In [19]:
news[["text", "clean_text"]].head()

,text,clean_text
22216,"21st Century Wire says Ben Stein, reputable pr...",st centuri wire say ben stein reput professor ...
4436,WASHINGTON (Reuters) - U.S. President Donald T...,washington reuter u presid donald trump remov ...
1526,(Reuters) - Puerto Rico Governor Ricardo Rosse...,reuter puerto rico governor ricardo rossello s...
1377,"On Monday, Donald Trump once again embarrassed...",monday donald trump embarrass countri accident...
8995,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",glasgow scotland reuter u presidenti candid go...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(news["clean_text"])
y = news["label"]

print(X.shape)
print(y.shape)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)

### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Logistic Regression Accuracy:", accuracy)

### Naive Bayes Classifier

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
nb_pred = nb_model.predict(X_test)
nb_accuracy = accuracy_score(y_test, nb_pred)
print("Naive Bayes Accuracy:", nb_accuracy)

### Linear Support Vector Machine (SVM)

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

svm_model = LinearSVC()
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_pred)
print("SVM Accuracy:", svm_accuracy)

### Random Forest Classifier

In [39]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)
print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.9966592427616926

### Decision Tree Classifier

In [40]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_pred)
print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.994543429844098

### Gradient Boosting Classifier

In [41]:
from sklearn.ensemble import GradientBoostingClassifier
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)
gb_pred = gb_model.predict(X_test)
gb_accuracy = accuracy_score(y_test, gb_pred)
print("Gradient Boosting Accuracy:", gb_accuracy)

Gradient Boosting Accuracy: 0.99543429844098

### K-Nearest Neighbors

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
knn_pred = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_pred)
print("KNN Accuracy:", knn_accuracy)

KNN Accuracy: 0.7402004454342984

In [44]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      4710
           1       0.98      0.99      0.98      4270

    accuracy                           0.98      8980
   macro avg       0.98      0.98      0.98      8980
weighted avg       0.98      0.98      0.98      8980

In [45]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[4622   88]
 [  54 4216]]

In [46]:
from sklearn.metrics import classification_report

print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4710
           1       0.99      0.99      0.99      4270

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

In [47]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, svm_pred)

print(cm)

[[4673   37]
 [  25 4245]]

In [48]:
import pandas as pd
results = pd.DataFrame({
    "Model": ["Naive Bayes", "Logistic Regression", "Linear SVM", "Random Forest", "Decision Tree", "Gradient Boosting", "KNN"],
    "Accuracy": [nb_accuracy, accuracy, svm_accuracy, rf_accuracy, dt_accuracy, gb_accuracy, knn_accuracy]
})
results_sorted = results.sort_values("Accuracy", ascending=False)
results_sorted

                 Model  Accuracy
3        Random Forest  0.996659
5    Gradient Boosting  0.995434
4        Decision Tree  0.994543
2           Linear SVM  0.993096
1  Logistic Regression  0.984187
0          Naive Bayes  0.924944
6                  KNN  0.740200

In [ ]:
import pickle

pickle.dump(rf_model, open("rf_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))